#!/usr/bin/env python3
"""
Script 5: Plot thesis-quality learning curves from Script 1 training logs.

Inputs:
- train_metrics.json  (generated by script1_train_jglaser.py)

Outputs:
- learning_curves/thesis_learning_curve.png
- learning_curves/best_epoch_summary.csv

Notes:
- This script uses only metrics that are actually present in train_metrics.json:
  epoch, train_loss, val_loss, val_rmse, val_pearson
- R² is NOT available from the current training logs, so it is not plotted.
"""

import json
import logging
from pathlib import Path

import pandas as pd

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
)
log = logging.getLogger(__name__)

WORK = Path(__file__).resolve().parent
METRICS_PATH = WORK / "train_metrics.json"
OUT_DIR = WORK / "learning_curves"
OUT_DIR.mkdir(exist_ok=True)


def main():
    if not METRICS_PATH.exists():
        raise FileNotFoundError(f"Could not find {METRICS_PATH}")

    with open(METRICS_PATH, "r") as f:
        history = json.load(f)

    if not history:
        raise ValueError("train_metrics.json is empty")

    df = pd.DataFrame(history)

    required_cols = ["epoch", "train_loss", "val_loss", "val_rmse", "val_pearson"]
    missing = [c for c in required_cols if c not in df.columns]
    if missing:
        raise ValueError(f"Missing required columns in train_metrics.json: {missing}")

    df = df.sort_values("epoch").reset_index(drop=True)

    best_loss_idx = df["val_loss"].idxmin()
    best_rmse_idx = df["val_rmse"].idxmin()
    best_r_idx = df["val_pearson"].idxmax()

    best_summary = pd.DataFrame([
        {
            "criterion": "best_val_loss",
            "epoch": int(df.loc[best_loss_idx, "epoch"]),
            "train_loss": float(df.loc[best_loss_idx, "train_loss"]),
            "val_loss": float(df.loc[best_loss_idx, "val_loss"]),
            "val_rmse": float(df.loc[best_loss_idx, "val_rmse"]),
            "val_pearson": float(df.loc[best_loss_idx, "val_pearson"]),
        },
        {
            "criterion": "best_val_rmse",
            "epoch": int(df.loc[best_rmse_idx, "epoch"]),
            "train_loss": float(df.loc[best_rmse_idx, "train_loss"]),
            "val_loss": float(df.loc[best_rmse_idx, "val_loss"]),
            "val_rmse": float(df.loc[best_rmse_idx, "val_rmse"]),
            "val_pearson": float(df.loc[best_rmse_idx, "val_pearson"]),
        },
        {
            "criterion": "best_val_pearson",
            "epoch": int(df.loc[best_r_idx, "epoch"]),
            "train_loss": float(df.loc[best_r_idx, "train_loss"]),
            "val_loss": float(df.loc[best_r_idx, "val_loss"]),
            "val_rmse": float(df.loc[best_r_idx, "val_rmse"]),
            "val_pearson": float(df.loc[best_r_idx, "val_pearson"]),
        },
    ])
    summary_path = OUT_DIR / "best_epoch_summary.csv"
    best_summary.to_csv(summary_path, index=False)
    log.info(f"Saved summary -> {summary_path}")

    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
    except ImportError:
        raise ImportError("matplotlib is required. Install it with: pip install matplotlib")

    plt.style.use("seaborn-v0_8-whitegrid")

    fig, axes = plt.subplots(1, 2, figsize=(14, 5.5))

    # Panel 1: loss curves
    ax1 = axes[0]
    ax1.plot(df["epoch"], df["train_loss"], marker="o", linewidth=2, color="tab:blue", label="Train loss")
    ax1.plot(df["epoch"], df["val_loss"], marker="s", linewidth=2, color="tab:orange", label="Validation loss")
    ax1.axvline(
        df.loc[best_loss_idx, "epoch"],
        linestyle="--",
        linewidth=1.5,
        color="black",
        alpha=0.8
    )
    ax1.scatter(
        df.loc[best_loss_idx, "epoch"],
        df.loc[best_loss_idx, "val_loss"],
        color="red",
        s=70,
        zorder=5
    )
    ax1.annotate(
        f"Best val loss = {df.loc[best_loss_idx, 'val_loss']:.4f}\n"
        f"Epoch = {int(df.loc[best_loss_idx, 'epoch'])}",
        xy=(df.loc[best_loss_idx, "epoch"], df.loc[best_loss_idx, "val_loss"]),
        xytext=(10, -35),
        textcoords="offset points",
        fontsize=10,
        bbox=dict(boxstyle="round,pad=0.3", fc="white", ec="gray", alpha=0.9)
    )
    ax1.set_xlabel("Epoch")
    ax1.set_ylabel("Loss")
    ax1.set_title("Training and Validation Loss")
    ax1.legend()

    # Panel 2: Pearson correlation
    ax2 = axes[1]
    ax2.plot(df["epoch"], df["val_pearson"], marker="o", linewidth=2, color="tab:green")
    ax2.axvline(
        df.loc[best_r_idx, "epoch"],
        linestyle="--",
        linewidth=1.5,
        color="black",
        alpha=0.8
    )
    ax2.scatter(
        df.loc[best_r_idx, "epoch"],
        df.loc[best_r_idx, "val_pearson"],
        color="red",
        s=70,
        zorder=5
    )
    ax2.annotate(
        f"Best Pearson r = {df.loc[best_r_idx, 'val_pearson']:.4f}\n"
        f"Epoch = {int(df.loc[best_r_idx, 'epoch'])}",
        xy=(df.loc[best_r_idx, "epoch"], df.loc[best_r_idx, "val_pearson"]),
        xytext=(10, -35),
        textcoords="offset points",
        fontsize=10,
        bbox=dict(boxstyle="round,pad=0.3", fc="white", ec="gray", alpha=0.9)
    )
    ax2.set_xlabel("Epoch")
    ax2.set_ylabel("Pearson r")
    ax2.set_title("Validation Pearson Correlation")

    fig.suptitle("Learning Curve of the Protein-Ligand Affinity Model", fontsize=14, y=1.03)
    fig.tight_layout()

    fig_path = OUT_DIR / "thesis_learning_curve.png"
    fig.savefig(fig_path, dpi=300, bbox_inches="tight")
    log.info(f"Saved plot -> {fig_path}")

    log.info("=" * 70)
    log.info("Script 5 complete.")
    log.info("=" * 70)


if __name__ == "__main__":
    main()